# Generated by Django 4.1.6 on 2023-07-04 05:26

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('done', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        # migrations.CreateModel(
        #     name='RoleActivation',
        #     fields=[
        #         ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
        #         ('is_active', models.BooleanField(default=True)),
        #     ],
        #     bases=('auth.group',),
        #     managers=[
        #         ('objects', django.contrib.auth.models.GroupManager()),
        #     ],
        # ),
    ]
