# Generated by Django 4.1.6 on 2023-07-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('done', '0002_customgroup_roleactivation'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='RoleActivation',
        # ),
    ]
