# Generated by Django 4.1.6 on 2023-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('done', '0003_delete_roleactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('team leader', 'Team Leader'), ('jr.developer', 'Jr. Developer'), ('sr.developer', 'Sr.Developer'), ('hr executive', 'HR Executive'), ('hr head', 'HR Head'), ('deactivated', 'Deactivated')], max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
